import java.util.*;

/**
 * AUTO-GENERATED TESTER — Q1b
 * Generated by IS442 Auto-Grading System v3.5 (LLM Oracle)
 * Test cases : 3
 */
public class Q1bTester extends Q1b {

    private static double score;
    private static String qn = "Q1b";

    public static void main(String[] args) {
        try {
            grade();
        } finally {
            System.out.printf("FINAL_SCORE:%.1f%n", score);
            System.exit(0);
        }
    }

    public static void grade() {
        System.out.println("-------------------------------------------------------");
        System.out.println("---------------------- " + qn + " ----------------------------");
        System.out.println("-------------------------------------------------------");

        int tcNum = 1;
        {
            try {
                ArrayList<Object> inputs = new ArrayList<>();
                inputs.add(10);
                inputs.add(20);
                inputs.add(30);
                System.out.printf("Test %d: getSumOfEvenIntegers(%s)%n", tcNum++, inputs);
                int expected0 = 60;
                int result0 = runWithTimeout(() -> Q1b.getSumOfEvenIntegers(new java.util.ArrayList<>(java.util.Arrays.asList(10, 20, 30))));
                System.out.printf("Expected  :|%s|%n", expected0);
                System.out.printf("Actual    :|%s|%n", result0);
                if (result0 == expected0) {
                    score += 1;
                    System.out.printf("PARTIAL_SCORE:%.1f%n", score);
                    System.out.println("Passed");
                } else {
                    System.out.println("Failed");
                }
            } catch (Exception e) {
                System.out.println("Failed -> Exception: " + e.getMessage());
            }
            System.out.println("-------------------------------------------------------");
        }

        {
            try {
                ArrayList<Object> inputs = new ArrayList<>();
                inputs.add(2);
                inputs.add(true);
                inputs.add("abc");
                inputs.add(1.0);
                System.out.printf("Test %d: getSumOfEvenIntegers(%s)%n", tcNum++, inputs);
                int expected1 = 2;
                int result1 = runWithTimeout(() -> Q1b.getSumOfEvenIntegers(new java.util.ArrayList<>(java.util.Arrays.asList(2, true, "abc", 1.0))));
                System.out.printf("Expected  :|%s|%n", expected1);
                System.out.printf("Actual    :|%s|%n", result1);
                if (result1 == expected1) {
                    score += 1;
                    System.out.printf("PARTIAL_SCORE:%.1f%n", score);
                    System.out.println("Passed");
                } else {
                    System.out.println("Failed");
                }
            } catch (Exception e) {
                System.out.println("Failed -> Exception: " + e.getMessage());
            }
            System.out.println("-------------------------------------------------------");
        }

        {
            try {
                ArrayList<Object> inputs = new ArrayList<>();
                inputs.add(10);
                inputs.add(20.0);
                inputs.add(30);
                System.out.printf("Test %d: getSumOfEvenIntegers(%s)%n", tcNum++, inputs);
                int expected2 = 40;
                int result2 = runWithTimeout(() -> Q1b.getSumOfEvenIntegers(new java.util.ArrayList<>(java.util.Arrays.asList(10, 20.0, 30))));
                System.out.printf("Expected  :|%s|%n", expected2);
                System.out.printf("Actual    :|%s|%n", result2);
                if (result2 == expected2) {
                    score += 1;
                    System.out.printf("PARTIAL_SCORE:%.1f%n", score);
                    System.out.println("Passed");
                } else {
                    System.out.println("Failed");
                }
            } catch (Exception e) {
                System.out.println("Failed -> Exception: " + e.getMessage());
            }
            System.out.println("-------------------------------------------------------");
        }

    }

    private static boolean eq(double a, double b) {
        return Math.abs(a - b) < 1e-9;
    }

    private static boolean eq(float a, float b) {
        return Math.abs(a - b) < 1e-6f;
    }

    private static boolean eq(Object a, Object b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        return a.equals(b);
    }

    private static boolean listToStringEq(java.util.List<?> a, java.util.List<?> b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        return a.toString().equals(b.toString());
    }

    private static boolean listEq(java.util.List<?> a, java.util.List<?> b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        if (a.size() != b.size()) return false;
        for (int i = 0; i < a.size(); i++) {
            Object ai = a.get(i), bi = b.get(i);
            if (ai == null && bi == null) continue;
            if (ai == null || !ai.equals(bi)) return false;
        }
        return true;
    }

    private static boolean setEq(java.util.Collection<?> a, java.util.Collection<?> b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        return new java.util.HashSet<>(a).equals(new java.util.HashSet<>(b));
    }

    private static <T> T runWithTimeout(java.util.concurrent.Callable<T> task) throws Exception {
        java.util.concurrent.ExecutorService exec = java.util.concurrent.Executors.newSingleThreadExecutor(r -> {
            Thread t = new Thread(r); t.setDaemon(true); return t;
        });
        java.util.concurrent.Future<T> future = exec.submit(task);
        try {
            return future.get(2, java.util.concurrent.TimeUnit.SECONDS);
        } catch (java.util.concurrent.TimeoutException | InterruptedException e) {
            future.cancel(true);
            throw new Exception("Timeout (Infinite Loop)");
        } catch (java.util.concurrent.ExecutionException e) {
            if (e.getCause() instanceof Exception) throw (Exception) e.getCause();
            throw new Exception(e.getCause());
        } finally {
            exec.shutdownNow();
        }
    }
}
