import java.util.*;

/**
 * AUTO-GENERATED TESTER — Q2a
 * Generated by IS442 Auto-Grading System v3.5 (LLM Oracle)
 * Test cases : 5
 */
public class Q2aTester extends Q2a {

    private static double score;
    private static String qn = "Q2a";

    public static void main(String[] args) {
        try {
            grade();
        } finally {
            System.out.printf("FINAL_SCORE:%.1f%n", score);
            System.exit(0);
        }
    }

    public static void grade() {
        System.out.println("-------------------------------------------------------");
        System.out.println("---------------------- " + qn + " ----------------------------");
        System.out.println("-------------------------------------------------------");

        int tcNum = 1;
        {
            try {
                System.out.printf("Test %d: getAverageAge(%s)%n", tcNum++, "persons.txt" + ", " + "LEE");
                double expected0 = 36.0;
                double result0 = runWithTimeout(() -> Q2a.getAverageAge("persons.txt", "LEE"));
                System.out.printf("Expected  :|%s|%n", expected0);
                System.out.printf("Actual    :|%s|%n", result0);
                if (eq(result0, expected0)) {
                    score += 1;
                    System.out.printf("PARTIAL_SCORE:%.1f%n", score);
                    System.out.println("Passed");
                } else {
                    System.out.println("Failed");
                }
            } catch (Exception e) {
                System.out.println("Failed -> Exception: " + e.getMessage());
            }
            System.out.println("-------------------------------------------------------");
        }

        {
            try {
                System.out.printf("Test %d: getAverageAge(%s)%n", tcNum++, "persons.txt" + ", " + "Lee");
                double expected1 = 36.0;
                double result1 = runWithTimeout(() -> Q2a.getAverageAge("persons.txt", "Lee"));
                System.out.printf("Expected  :|%s|%n", expected1);
                System.out.printf("Actual    :|%s|%n", result1);
                if (eq(result1, expected1)) {
                    score += 1;
                    System.out.printf("PARTIAL_SCORE:%.1f%n", score);
                    System.out.println("Passed");
                } else {
                    System.out.println("Failed");
                }
            } catch (Exception e) {
                System.out.println("Failed -> Exception: " + e.getMessage());
            }
            System.out.println("-------------------------------------------------------");
        }

        {
            try {
                System.out.printf("Test %d: getAverageAge(%s)%n", tcNum++, "persons.txt" + ", " + "WONG");
                double expected2 = 25.0;
                double result2 = runWithTimeout(() -> Q2a.getAverageAge("persons.txt", "WONG"));
                System.out.printf("Expected  :|%s|%n", expected2);
                System.out.printf("Actual    :|%s|%n", result2);
                if (eq(result2, expected2)) {
                    score += 1;
                    System.out.printf("PARTIAL_SCORE:%.1f%n", score);
                    System.out.println("Passed");
                } else {
                    System.out.println("Failed");
                }
            } catch (Exception e) {
                System.out.println("Failed -> Exception: " + e.getMessage());
            }
            System.out.println("-------------------------------------------------------");
        }

        {
            try {
                System.out.printf("Test %d: getAverageAge(%s)%n", tcNum++, "persons.txt" + ", " + "Chan");
                double expected3 = 27.0;
                double result3 = runWithTimeout(() -> Q2a.getAverageAge("persons.txt", "Chan"));
                System.out.printf("Expected  :|%s|%n", expected3);
                System.out.printf("Actual    :|%s|%n", result3);
                if (eq(result3, expected3)) {
                    score += 1;
                    System.out.printf("PARTIAL_SCORE:%.1f%n", score);
                    System.out.println("Passed");
                } else {
                    System.out.println("Failed");
                }
            } catch (Exception e) {
                System.out.println("Failed -> Exception: " + e.getMessage());
            }
            System.out.println("-------------------------------------------------------");
        }

        {
            try {
                System.out.printf("Test %d: getAverageAge(%s)%n", tcNum++, "persons.txt" + ", " + "Ong");
                double expected4 = 0.0;
                double result4 = runWithTimeout(() -> Q2a.getAverageAge("persons.txt", "Ong"));
                System.out.printf("Expected  :|%s|%n", expected4);
                System.out.printf("Actual    :|%s|%n", result4);
                if (eq(result4, expected4)) {
                    score += 1;
                    System.out.printf("PARTIAL_SCORE:%.1f%n", score);
                    System.out.println("Passed");
                } else {
                    System.out.println("Failed");
                }
            } catch (Exception e) {
                System.out.println("Failed -> Exception: " + e.getMessage());
            }
            System.out.println("-------------------------------------------------------");
        }

    }

    private static boolean eq(double a, double b) {
        return Math.abs(a - b) < 1e-9;
    }

    private static boolean eq(float a, float b) {
        return Math.abs(a - b) < 1e-6f;
    }

    private static boolean eq(Object a, Object b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        return a.equals(b);
    }

    private static boolean listToStringEq(java.util.List<?> a, java.util.List<?> b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        return a.toString().equals(b.toString());
    }

    private static boolean listEq(java.util.List<?> a, java.util.List<?> b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        if (a.size() != b.size()) return false;
        for (int i = 0; i < a.size(); i++) {
            Object ai = a.get(i), bi = b.get(i);
            if (ai == null && bi == null) continue;
            if (ai == null || !ai.equals(bi)) return false;
        }
        return true;
    }

    private static boolean setEq(java.util.Collection<?> a, java.util.Collection<?> b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        return new java.util.HashSet<>(a).equals(new java.util.HashSet<>(b));
    }

    private static <T> T runWithTimeout(java.util.concurrent.Callable<T> task) throws Exception {
        java.util.concurrent.ExecutorService exec = java.util.concurrent.Executors.newSingleThreadExecutor(r -> {
            Thread t = new Thread(r); t.setDaemon(true); return t;
        });
        java.util.concurrent.Future<T> future = exec.submit(task);
        try {
            return future.get(2, java.util.concurrent.TimeUnit.SECONDS);
        } catch (java.util.concurrent.TimeoutException | InterruptedException e) {
            future.cancel(true);
            throw new Exception("Timeout (Infinite Loop)");
        } catch (java.util.concurrent.ExecutionException e) {
            if (e.getCause() instanceof Exception) throw (Exception) e.getCause();
            throw new Exception(e.getCause());
        } finally {
            exec.shutdownNow();
        }
    }
}
