import java.util.*;

/**
 * AUTO-GENERATED TESTER — Q2b
 * Generated by IS442 Auto-Grading System v3.5 (LLM Oracle)
 * Test cases : 5
 */
public class Q2bTester extends Q2b {

    private static double score;
    private static String qn = "Q2b";

    public static void main(String[] args) {
        try {
            grade();
        } finally {
            System.out.printf("FINAL_SCORE:%.1f%n", score);
            System.exit(0);
        }
    }

    public static void grade() {
        System.out.println("-------------------------------------------------------");
        System.out.println("---------------------- " + qn + " ----------------------------");
        System.out.println("-------------------------------------------------------");

        int tcNum = 1;
        {
            try {
                System.out.printf("Test %d: getTopStudent(%s)%n", tcNum++, "students.txt" + ", " + "IS101");
                String expected0 = "John LEE-4.0";
                String result0 = runWithTimeout(() -> Q2b.getTopStudent("students.txt", "IS101"));
                System.out.printf("Expected  :|%s|%n", expected0);
                System.out.printf("Actual    :|%s|%n", result0);
                if (eq((Object)result0, (Object)expected0)) {
                    score += 1;
                    System.out.printf("PARTIAL_SCORE:%.1f%n", score);
                    System.out.println("Passed");
                } else {
                    System.out.println("Failed");
                }
            } catch (Exception e) {
                System.out.println("Failed -> Exception: " + e.getMessage());
            }
            System.out.println("-------------------------------------------------------");
        }

        {
            try {
                System.out.printf("Test %d: getTopStudent(%s)%n", tcNum++, "students.txt" + ", " + "IS102");
                String expected1 = "Mary CHAN-3.5";
                String result1 = runWithTimeout(() -> Q2b.getTopStudent("students.txt", "IS102"));
                System.out.printf("Expected  :|%s|%n", expected1);
                System.out.printf("Actual    :|%s|%n", result1);
                if (eq((Object)result1, (Object)expected1)) {
                    score += 1;
                    System.out.printf("PARTIAL_SCORE:%.1f%n", score);
                    System.out.println("Passed");
                } else {
                    System.out.println("Failed");
                }
            } catch (Exception e) {
                System.out.println("Failed -> Exception: " + e.getMessage());
            }
            System.out.println("-------------------------------------------------------");
        }

        {
            try {
                System.out.printf("Test %d: getTopStudent(%s)%n", tcNum++, "students.txt" + ", " + "IS103");
                String expected2 = "CHAN Wei Jun-4.0";
                String result2 = runWithTimeout(() -> Q2b.getTopStudent("students.txt", "IS103"));
                System.out.printf("Expected  :|%s|%n", expected2);
                System.out.printf("Actual    :|%s|%n", result2);
                if (eq((Object)result2, (Object)expected2)) {
                    score += 1;
                    System.out.printf("PARTIAL_SCORE:%.1f%n", score);
                    System.out.println("Passed");
                } else {
                    System.out.println("Failed");
                }
            } catch (Exception e) {
                System.out.println("Failed -> Exception: " + e.getMessage());
            }
            System.out.println("-------------------------------------------------------");
        }

        {
            try {
                System.out.printf("Test %d: getTopStudent(%s)%n", tcNum++, "students.txt" + ", " + "IS104");
                Object __dummy = runWithTimeout(() -> Q2b.getTopStudent("students.txt", "IS104"));
                System.out.println("Expected  :|DataException thrown|");
                System.out.println("Actual    :|no exception — FAILED|");
                System.out.println("Failed");
            } catch (DataException e) {
                System.out.println("Expected  :|DataException thrown|");
                System.out.println("Actual    :|DataException thrown|");
                score += 1;
                System.out.printf("PARTIAL_SCORE:%.1f%n", score);
                System.out.println("Passed");
            } catch (Exception e) {
                System.out.println("Expected  :|DataException thrown|");
                System.out.println("Actual    :|wrong exception: " + e.getClass().getSimpleName() + "|"  );
                System.out.println("Failed");
            }
            System.out.println("-------------------------------------------------------");
        }

        {
            try {
                System.out.printf("Test %d: getTopStudent(%s)%n", tcNum++, "nosuchfile.txt" + ", " + "IS101");
                Object __dummy = runWithTimeout(() -> Q2b.getTopStudent("nosuchfile.txt", "IS101"));
                System.out.println("Expected  :|DataException thrown|");
                System.out.println("Actual    :|no exception — FAILED|");
                System.out.println("Failed");
            } catch (DataException e) {
                System.out.println("Expected  :|DataException thrown|");
                System.out.println("Actual    :|DataException thrown|");
                score += 1;
                System.out.printf("PARTIAL_SCORE:%.1f%n", score);
                System.out.println("Passed");
            } catch (Exception e) {
                System.out.println("Expected  :|DataException thrown|");
                System.out.println("Actual    :|wrong exception: " + e.getClass().getSimpleName() + "|"  );
                System.out.println("Failed");
            }
            System.out.println("-------------------------------------------------------");
        }

    }

    private static boolean eq(double a, double b) {
        return Math.abs(a - b) < 1e-9;
    }

    private static boolean eq(float a, float b) {
        return Math.abs(a - b) < 1e-6f;
    }

    private static boolean eq(Object a, Object b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        return a.equals(b);
    }

    private static boolean listToStringEq(java.util.List<?> a, java.util.List<?> b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        return a.toString().equals(b.toString());
    }

    private static boolean listEq(java.util.List<?> a, java.util.List<?> b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        if (a.size() != b.size()) return false;
        for (int i = 0; i < a.size(); i++) {
            Object ai = a.get(i), bi = b.get(i);
            if (ai == null && bi == null) continue;
            if (ai == null || !ai.equals(bi)) return false;
        }
        return true;
    }

    private static boolean setEq(java.util.Collection<?> a, java.util.Collection<?> b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        return new java.util.HashSet<>(a).equals(new java.util.HashSet<>(b));
    }

    private static <T> T runWithTimeout(java.util.concurrent.Callable<T> task) throws Exception {
        java.util.concurrent.ExecutorService exec = java.util.concurrent.Executors.newSingleThreadExecutor(r -> {
            Thread t = new Thread(r); t.setDaemon(true); return t;
        });
        java.util.concurrent.Future<T> future = exec.submit(task);
        try {
            return future.get(2, java.util.concurrent.TimeUnit.SECONDS);
        } catch (java.util.concurrent.TimeoutException | InterruptedException e) {
            future.cancel(true);
            throw new Exception("Timeout (Infinite Loop)");
        } catch (java.util.concurrent.ExecutionException e) {
            if (e.getCause() instanceof Exception) throw (Exception) e.getCause();
            throw new Exception(e.getCause());
        } finally {
            exec.shutdownNow();
        }
    }
}
