import java.util.*;

/**
 * AUTO-GENERATED TESTER — Q3
 * Generated by IS442 Auto-Grading System v3.5 (LLM Oracle)
 * Test cases : 4
 */
public class Q3Tester extends Q3 {

    private static double score;
    private static String qn = "Q3";

    public static void main(String[] args) {
        try {
            grade();
        } finally {
            System.out.printf("FINAL_SCORE:%.1f%n", score);
            System.exit(0);
        }
    }

    public static void grade() {
        System.out.println("-------------------------------------------------------");
        System.out.println("---------------------- " + qn + " ----------------------------");
        System.out.println("-------------------------------------------------------");

        int tcNum = 1;
        {
            try {
                ArrayList<Shape> inputs = new ArrayList<>();
                inputs.add(new Rectangle("R1", 1000, 2));
                inputs.add(new Rectangle("R2", 4, 2.5));
                inputs.add(new Circle("C1", 50));
                System.out.printf("Test %d: sortShapes(%s)%n", tcNum++, inputs);
                String expected = "[R2=>10.0:13.0]";
                List<Shape> result = runWithTimeout(() -> Q3.sortShapes(new java.util.ArrayList<Shape>(java.util.Arrays.asList(new Rectangle("R1", 1000, 2), new Rectangle("R2", 4, 2.5), new Circle("C1", 50)))));
                System.out.printf("Expected  :|%s|%n", expected);
                System.out.printf("Actual    :|%s|%n", result);
                if (result != null && result.toString().equals(expected)) {
                    score += 1;
                    System.out.printf("PARTIAL_SCORE:%.1f%n", score);
                    System.out.println("Passed");
                } else {
                    System.out.println("Failed");
                }
            } catch (Exception e) {
                System.out.println("Failed -> Exception: " + e.getMessage());
            }
            System.out.println("-------------------------------------------------------");
        }

        {
            try {
                ArrayList<Shape> inputs = new ArrayList<>();
                inputs.add(new Rectangle("R1", 10, 2));
                inputs.add(new Rectangle("R2", 4, 2.5));
                inputs.add(new Rectangle("R3", 5, 6));
                System.out.printf("Test %d: sortShapes(%s)%n", tcNum++, inputs);
                String expected = "[R3=>30.0:22.0, R1=>20.0:24.0, R2=>10.0:13.0]";
                List<Shape> result = runWithTimeout(() -> Q3.sortShapes(new java.util.ArrayList<Shape>(java.util.Arrays.asList(new Rectangle("R1", 10, 2), new Rectangle("R2", 4, 2.5), new Rectangle("R3", 5, 6)))));
                System.out.printf("Expected  :|%s|%n", expected);
                System.out.printf("Actual    :|%s|%n", result);
                if (result != null && result.toString().equals(expected)) {
                    score += 1;
                    System.out.printf("PARTIAL_SCORE:%.1f%n", score);
                    System.out.println("Passed");
                } else {
                    System.out.println("Failed");
                }
            } catch (Exception e) {
                System.out.println("Failed -> Exception: " + e.getMessage());
            }
            System.out.println("-------------------------------------------------------");
        }

        {
            try {
                ArrayList<Shape> inputs = new ArrayList<>();
                inputs.add(new Rectangle("R1", 8, 3));
                inputs.add(new Rectangle("R2", 6, 4));
                inputs.add(new Rectangle("R3", 12, 2));
                System.out.printf("Test %d: sortShapes(%s)%n", tcNum++, inputs);
                String expected = "[R3=>24.0:28.0, R1=>24.0:22.0, R2=>24.0:20.0]";
                List<Shape> result = runWithTimeout(() -> Q3.sortShapes(new java.util.ArrayList<Shape>(java.util.Arrays.asList(new Rectangle("R1", 8, 3), new Rectangle("R2", 6, 4), new Rectangle("R3", 12, 2)))));
                System.out.printf("Expected  :|%s|%n", expected);
                System.out.printf("Actual    :|%s|%n", result);
                if (result != null && result.toString().equals(expected)) {
                    score += 1;
                    System.out.printf("PARTIAL_SCORE:%.1f%n", score);
                    System.out.println("Passed");
                } else {
                    System.out.println("Failed");
                }
            } catch (Exception e) {
                System.out.println("Failed -> Exception: " + e.getMessage());
            }
            System.out.println("-------------------------------------------------------");
        }

        {
            try {
                ArrayList<Shape> inputs = new ArrayList<>();
                inputs.add(new Rectangle("R1", 8, 3));
                inputs.add(new Rectangle("R2", 12, 2));
                inputs.add(new Circle("C1", 10));
                inputs.add(new Circle("C2", 1));
                System.out.printf("Test %d: sortShapes(%s)%n", tcNum++, inputs);
                String expected = "[C1=>314.0:63.0, R2=>24.0:28.0, R1=>24.0:22.0, C2=>3.0:6.0]";
                List<Shape> result = runWithTimeout(() -> Q3.sortShapes(new java.util.ArrayList<Shape>(java.util.Arrays.asList(new Rectangle("R1", 8, 3), new Rectangle("R2", 12, 2), new Circle("C1", 10), new Circle("C2", 1)))));
                System.out.printf("Expected  :|%s|%n", expected);
                System.out.printf("Actual    :|%s|%n", result);
                if (result != null && result.toString().equals(expected)) {
                    score += 1;
                    System.out.printf("PARTIAL_SCORE:%.1f%n", score);
                    System.out.println("Passed");
                } else {
                    System.out.println("Failed");
                }
            } catch (Exception e) {
                System.out.println("Failed -> Exception: " + e.getMessage());
            }
            System.out.println("-------------------------------------------------------");
        }

    }

    private static boolean eq(double a, double b) {
        return Math.abs(a - b) < 1e-9;
    }

    private static boolean eq(float a, float b) {
        return Math.abs(a - b) < 1e-6f;
    }

    private static boolean eq(Object a, Object b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        return a.equals(b);
    }

    private static boolean listToStringEq(java.util.List<?> a, java.util.List<?> b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        return a.toString().equals(b.toString());
    }

    private static boolean listEq(java.util.List<?> a, java.util.List<?> b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        if (a.size() != b.size()) return false;
        for (int i = 0; i < a.size(); i++) {
            Object ai = a.get(i), bi = b.get(i);
            if (ai == null && bi == null) continue;
            if (ai == null || !ai.equals(bi)) return false;
        }
        return true;
    }

    private static boolean setEq(java.util.Collection<?> a, java.util.Collection<?> b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        return new java.util.HashSet<>(a).equals(new java.util.HashSet<>(b));
    }

    private static <T> T runWithTimeout(java.util.concurrent.Callable<T> task) throws Exception {
        java.util.concurrent.ExecutorService exec = java.util.concurrent.Executors.newSingleThreadExecutor(r -> {
            Thread t = new Thread(r); t.setDaemon(true); return t;
        });
        java.util.concurrent.Future<T> future = exec.submit(task);
        try {
            return future.get(2, java.util.concurrent.TimeUnit.SECONDS);
        } catch (java.util.concurrent.TimeoutException | InterruptedException e) {
            future.cancel(true);
            throw new Exception("Timeout (Infinite Loop)");
        } catch (java.util.concurrent.ExecutionException e) {
            if (e.getCause() instanceof Exception) throw (Exception) e.getCause();
            throw new Exception(e.getCause());
        } finally {
            exec.shutdownNow();
        }
    }
}
