package com.autogradingsystem.testcasegenerator.service;

import com.autogradingsystem.testcasegenerator.model.GeneratedTestCase;
import com.autogradingsystem.testcasegenerator.model.QuestionSpec;
import com.autogradingsystem.testcasegenerator.model.QuestionSpec.MethodSpec;
import com.autogradingsystem.testcasegenerator.model.QuestionSpec.ParamSpec;

import java.util.*;

/**
 * TesterGenerator - Generates *Tester.java source matching the IS442 tester format.
 */
public class TesterGenerator {

    private final LLMTestOracle oracle;

    private static final Set<String> SAFE_EQUALS_TYPES = Set.of(
            "String", "Integer", "Long", "Double", "Float",
            "Boolean", "Character", "int", "long", "double",
            "float", "boolean", "char", "Object"
    );

    public TesterGenerator() {
        this.oracle = LLMTestOracle.fromEnvironment();
    }

    public TesterGenerator(LLMTestOracle oracle) {
        this.oracle = oracle;
    }

    // -------------------------------------------------------------------------
    // Entry point
    // -------------------------------------------------------------------------

    public String generate(String questionId, QuestionSpec spec, int numTests) {
        String testerClassName = questionId + "Tester";
        String studentClass    = spec.getClassName() != null ? spec.getClassName() : questionId;
        boolean canExtend      = canExtend(spec);

        List<MethodSpec> testable = pickTestableMethods(spec);

        List<GeneratedTestCase> testCases = new ArrayList<>();
        if (!testable.isEmpty()) {
            testCases = oracle.generateTestCases(questionId, spec, testable, numTests);
        }

        StringBuilder sb = new StringBuilder();
        sb.append("import java.util.*;\n\n");
        sb.append("/**\n * AUTO-GENERATED TESTER — ").append(questionId).append("\n");
        sb.append(" * Generated by IS442 Auto-Grading System v3.5 (LLM Oracle)\n");
        sb.append(" * Test cases : ").append(numTests).append("\n */\n");

        if (canExtend) {
            sb.append("public class ").append(testerClassName)
              .append(" extends ").append(studentClass).append(" {\n\n");
        } else {
            sb.append("public class ").append(testerClassName).append(" {\n\n");
        }

        sb.append("    private static double score;\n");
        sb.append("    private static String qn = \"").append(questionId).append("\";\n\n");

        sb.append("    public static void main(String[] args) {\n");
        sb.append("        grade();\n");
        sb.append("        System.out.println(score);\n");
        sb.append("    }\n\n");

        sb.append("    public static void grade() {\n");
        sb.append("        System.out.println(\"-------------------------------------------------------\");\n");
        sb.append("        System.out.println(\"---------------------- \" + qn + \" ----------------------------\");\n");
        sb.append("        System.out.println(\"-------------------------------------------------------\");\n\n");
        sb.append("        int tcNum = 1;\n");

        if (testable.isEmpty()) {
            appendCompileOnlyTests(sb, studentClass, canExtend, numTests);
        } else {
            appendMethodTests(sb, studentClass, canExtend, testable, testCases, numTests);
        }

        sb.append("    }\n\n");
        appendHelpers(sb);
        sb.append("}\n");
        return sb.toString();
    }

    // =========================================================================
    // Method test rendering
    // =========================================================================

    private void appendMethodTests(StringBuilder sb, String studentClass,
                                   boolean canExtend, List<MethodSpec> testable,
                                   List<GeneratedTestCase> testCases, int numTests) {
        for (int i = 0; i < numTests; i++) {
            MethodSpec method = testable.get(i % testable.size());
            GeneratedTestCase tc = i < testCases.size()
                    ? testCases.get(i)
                    : GeneratedTestCase.smokeTest(List.of(), "fallback");
            appendSingleTest(sb, studentClass, canExtend, method, tc, i, numTests);
        }
    }

    private void appendSingleTest(StringBuilder sb, String studentClass,
                                  boolean canExtend, MethodSpec method,
                                  GeneratedTestCase tc, int testIndex, int numTests) {

        List<String> argLiterals = buildArgLiterals(tc, method, testIndex);
        argLiterals = stripObjectCasts(argLiterals, method);

        String retType  = method.getReturnType();
        String javaRet  = javaType(retType);
        String strategy = resolveStrategy(tc, retType);
        boolean isVoid  = method.returnsVoid() || tc.isVoidCheck();
        boolean isSmoke = tc.isSmokeTest();
        boolean expectsException = "exception".equals(tc.getEqualityStrategy());

        // Build call — use inherited (no class prefix) when tester extends student class
        String callExpr;
        if (canExtend && !method.isStatic()) {
            callExpr = method.getName() + "(" + String.join(", ", argLiterals) + ")";
        } else {
            callExpr = studentClass + "." + method.getName()
                     + "(" + String.join(", ", argLiterals) + ")";
        }

        sb.append("        {\n");
        sb.append("            try {\n");

        // Build input variables in IS442 readable format (ArrayList + .add() calls)
        String inputExpr = buildInputBlock(sb, argLiterals, method, testIndex);

        sb.append("                System.out.printf(\"Test %d: ")
          .append(method.getName()).append("(%s)%n\", tcNum++, ")
          .append(inputExpr).append(");\n");

        if (expectsException) {
            String exClass = tc.getExpected() != null
                    ? tc.getExpected().replace("\"", "").trim() : "Exception";
            if (!exClass.matches("[A-Za-z][A-Za-z0-9_]*")) exClass = "Exception";
            sb.append("                ").append(callExpr).append(";\n");
            sb.append("                System.out.println(\"Expected  :|").append(exClass).append(" thrown|\");\n");
            sb.append("                System.out.println(\"Actual    :|no exception — FAILED|\");\n");
            sb.append("                System.out.println(\"Failed\");\n");
            sb.append("            } catch (").append(exClass).append(" e) {\n");
            sb.append("                System.out.println(\"Expected  :|").append(exClass).append(" thrown|\");\n");
            sb.append("                System.out.println(\"Actual    :|").append(exClass).append(" thrown|\");\n");
            sb.append("                score += 1;\n");
            sb.append("                System.out.println(\"Passed\");\n");
            sb.append("            } catch (Exception e) {\n");
            sb.append("                System.out.println(\"Expected  :|").append(exClass).append(" thrown|\");\n");
            sb.append("                System.out.println(\"Actual    :|wrong exception: \" + e.getClass().getSimpleName() + \"|\"  );\n");
            sb.append("                System.out.println(\"Failed\");\n");
            sb.append("            }\n");

        } else if (isVoid || isSmoke) {
            sb.append("                ").append(callExpr).append(";\n");
            sb.append("                System.out.println(\"Expected  :|no exception|\");\n");
            sb.append("                System.out.println(\"Actual    :|no exception|\");\n");
            sb.append("                score += 1;\n");
            sb.append("                System.out.println(\"Passed\");\n");
            sb.append("            } catch (Exception e) {\n");
            sb.append("                System.out.println(\"Expected  :|no exception|\");\n");
            sb.append("                System.out.println(\"Actual    :|exception: \" + e.getClass().getSimpleName() + \"|\"  );\n");
            sb.append("                System.out.println(\"Failed\");\n");
            sb.append("            }\n");

        } else if ("toString_equals".equals(strategy)) {
            String expectedExpr = tc.getExpected() != null ? tc.getExpected() : "\"\"\"";
            sb.append("                String expected = ").append(expectedExpr).append(";\n");
            sb.append("                ").append(javaRet).append(" result = ").append(callExpr).append(";\n");
            sb.append("                System.out.printf(\"Expected  :|%s|%n\", expected);\n");
            sb.append("                System.out.printf(\"Actual    :|%s|%n\", result);\n");
            sb.append("                if (result != null && result.toString().equals(expected)) {\n");
            sb.append("                    score += 1;\n");
            sb.append("                    System.out.println(\"Passed\");\n");
            sb.append("                } else {\n");
            sb.append("                    System.out.println(\"Failed\");\n");
            sb.append("                }\n");
            sb.append("            } catch (Exception e) {\n");
            sb.append("                System.out.println(\"Failed -> Exception: \" + e.getMessage());\n");
            sb.append("            }\n");

        } else if ("list_equals".equals(strategy)
                || (isListType(retType) && !isCustomObjectList(retType))) {
            // List equality — use .equals() directly, matching IS442 tester format
            String expectedExpr = tc.getExpected() != null ? tc.getExpected() : "new java.util.ArrayList<>()";
            String evName = "expected" + testIndex;
            String rvName = "result"   + testIndex;
            sb.append("                ").append(javaRet).append(" ").append(evName)
              .append(" = ").append(expectedExpr).append(";\n");
            sb.append("                ").append(javaRet).append(" ").append(rvName)
              .append(" = ").append(callExpr).append(";\n");
            sb.append("                System.out.printf(\"Expected  :|%s|%n\", ").append(evName).append(");\n");
            sb.append("                System.out.printf(\"Actual    :|%s|%n\", ").append(rvName).append(");\n");
            sb.append("                if (").append(evName).append(".equals(").append(rvName).append(")) {\n");
            sb.append("                    score += 1;\n");
            sb.append("                    System.out.println(\"Passed\");\n");
            sb.append("                } else {\n");
            sb.append("                    System.out.println(\"Failed\");\n");
            sb.append("                }\n");
            sb.append("            } catch (Exception e) {\n");
            sb.append("                System.out.println(\"Failed -> Exception\");\n");
            sb.append("                e.printStackTrace();\n");
            sb.append("            }\n");

        } else {
            // Primitive / String / boxed type equality
            String expectedExpr = tc.getExpected() != null ? tc.getExpected() : "null";
            String evName = "expected" + testIndex;
            String rvName = "result"   + testIndex;
            sb.append("                ").append(javaRet).append(" ").append(evName)
              .append(" = ").append(expectedExpr).append(";\n");
            sb.append("                ").append(javaRet).append(" ").append(rvName)
              .append(" = ").append(callExpr).append(";\n");
            sb.append("                System.out.printf(\"Expected  :|%s|%n\", ").append(evName).append(");\n");
            sb.append("                System.out.printf(\"Actual    :|%s|%n\", ").append(rvName).append(");\n");
            String cond = buildCondition(rvName, evName, strategy, javaRet);
            sb.append("                if (").append(cond).append(") {\n");
            sb.append("                    score += 1;\n");
            sb.append("                    System.out.println(\"Passed\");\n");
            sb.append("                } else {\n");
            sb.append("                    System.out.println(\"Failed\");\n");
            sb.append("                }\n");
            sb.append("            } catch (Exception e) {\n");
            sb.append("                System.out.println(\"Failed -> Exception\");\n");
            sb.append("                e.printStackTrace();\n");
            sb.append("            }\n");
        }

        sb.append("            System.out.println(\"-------------------------------------------------------\");\n");
        sb.append("        }\n\n");
    }

    /**
     * Builds input variable declarations in readable IS442 format.
     * Collections use ArrayList + .add() calls (matches Q1aTester.java style).
     * Returns the expression to use in System.out.printf for the input display.
     */
    private String buildInputBlock(StringBuilder sb, List<String> argLiterals,
                                   MethodSpec method, int testIndex) {
        if (argLiterals.isEmpty()) return "\"\"\"";

        if (argLiterals.size() == 1) {
            String arg = argLiterals.get(0);
            if (!isCollectionExpression(arg)) return arg;
            String varName  = "inputs";
            String elemType = inferElemType(arg, method, 0);
            sb.append("                ArrayList<").append(elemType).append("> ").append(varName)
              .append(" = new ArrayList<>();\n");
            appendAddCalls(sb, arg, varName);
            return varName;
        }

        // Multiple args
        List<String> varRefs = new ArrayList<>();
        for (int i = 0; i < argLiterals.size(); i++) {
            String arg = argLiterals.get(i);
            if (isCollectionExpression(arg)) {
                String varName  = "inputs" + i;
                String elemType = inferElemType(arg, method, i);
                sb.append("                ArrayList<").append(elemType).append("> ").append(varName)
                  .append(" = new ArrayList<>();\n");
                appendAddCalls(sb, arg, varName);
                varRefs.add(varName);
            } else {
                varRefs.add(arg);
            }
        }
        if (varRefs.size() == 1) return varRefs.get(0);
        StringBuilder joined = new StringBuilder();
        for (int i = 0; i < varRefs.size(); i++) {
            if (i > 0) joined.append(" + \", \" + ");
            joined.append(varRefs.get(i));
        }
        return joined.toString();
    }

    private boolean isCollectionExpression(String arg) {
        return arg != null && (arg.contains("Arrays.asList") || arg.contains("ArrayList"));
    }

    private String inferElemType(String arg, MethodSpec method, int paramIndex) {
        if (method.getParams().size() > paramIndex) {
            String t = extractGenericType(method.getParams().get(paramIndex).getType());
            if (!"Object".equals(t)) return t;
        }
        if (arg.contains("\\\"") || arg.contains("\"\\")) return "String";
        int asIdx = arg.indexOf("asList(");
        if (asIdx >= 0) {
            int p = arg.indexOf('(', asIdx) + 1;
            int e = arg.indexOf(')', p);
            if (e > p) {
                String first = arg.substring(p, e).split(",")[0].trim();
                if (first.startsWith("\"")) return "String";
                if (first.matches("-?\\d+")) return "Integer";
                if (first.matches("-?\\d+\\..*")) return "Double";
            }
        }
        return "Object";
    }

    private void appendAddCalls(StringBuilder sb, String arg, String varName) {
        int start = arg.indexOf("asList(");
        if (start < 0) return;
        int parenStart = arg.indexOf('(', start);
        if (parenStart < 0) return;
        int depth = 1, idx = parenStart + 1;
        while (idx < arg.length() && depth > 0) {
            char c = arg.charAt(idx);
            if (c == '(') depth++;
            else if (c == ')') depth--;
            idx++;
        }
        String inner = arg.substring(parenStart + 1, idx - 1).trim();
        if (inner.isEmpty()) return;
        for (String elem : splitTopLevel(inner)) {
            elem = elem.trim();
            if (!elem.isEmpty())
                sb.append("                ").append(varName).append(".add(").append(elem).append(");\n");
        }
    }

    private List<String> splitTopLevel(String s) {
        List<String> parts = new ArrayList<>();
        int depth = 0, start = 0;
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c == '(' || c == '<') depth++;
            else if (c == ')' || c == '>') depth--;
            else if (c == ',' && depth == 0) {
                parts.add(s.substring(start, i));
                start = i + 1;
            }
        }
        parts.add(s.substring(start));
        return parts;
    }

    private boolean isCustomObjectList(String type) {
        if (type == null) return false;
        String elem = extractGenericType(type);
        return !SAFE_EQUALS_TYPES.contains(elem) && !"Object".equals(elem);
    }

    private List<String> stripObjectCasts(List<String> args, MethodSpec method) {
        List<ParamSpec> params = method.getParams();
        List<String> result = new ArrayList<>();
        for (int i = 0; i < args.size(); i++) {
            String arg = args.get(i);
            String paramType = i < params.size() ? params.get(i).getType() : "";
            if (isListType(paramType)) {
                String elemType = extractGenericType(paramType);
                if (!elemType.equals("Object") && !elemType.isBlank()) {
                    // Use explicit type to fix Java type inference e.g. new ArrayList<Shape>(...)
                    arg = arg.replace("new java.util.ArrayList<>(",
                                      "new java.util.ArrayList<" + elemType + ">(");
                    // Strip (Object) casts — invalid for typed lists
                    arg = arg.replace("(Object)", "");
                }
            }
            // Strip qualified class names like ShapeComparator.Rectangle -> Rectangle
            // LLM sometimes thinks concrete classes are inner classes of helper files
            arg = arg.replaceAll("new \\w+\\.(Rectangle|Circle|Shape)\\(", "new $1(");
            result.add(arg);
        }
        return result;
    }

    // =========================================================================
    // Compile-only fallback
    // =========================================================================

    private void appendCompileOnlyTests(StringBuilder sb, String studentClass,
                                        boolean canExtend, int numTests) {
        sb.append("        // No public methods discovered — compile check only\n");
        for (int i = 0; i < numTests; i++) {
            sb.append("        {\n");
            sb.append("            try {\n");
            sb.append("                System.out.printf(\"Test %d: instantiation%n\", tcNum++);\n");
            if (!canExtend) {
                sb.append("                ").append(studentClass).append(" obj = new ")
                  .append(studentClass).append("();\n");
                sb.append("                System.out.printf(\"Expected  :|not null|%n\");\n");
                sb.append("                System.out.printf(\"Actual    :|%s|%n\", obj != null ? \"not null\" : \"null\");\n");
                sb.append("                if (obj != null) {\n");
            } else {
                sb.append("                System.out.printf(\"Expected  :|compiled|%n\");\n");
                sb.append("                System.out.printf(\"Actual    :|compiled|%n\");\n");
                sb.append("                if (true) {\n");
            }
            sb.append("                    score += 1;\n");
            sb.append("                    System.out.printf(\"PARTIAL_SCORE:%.1f%n\", score);\n");
            sb.append("                    System.out.println(\"Passed\");\n");
            sb.append("                } else {\n");
            sb.append("                    System.out.println(\"Failed\");\n");
            sb.append("                }\n");
            sb.append("            } catch (Exception e) {\n");
            sb.append("                System.out.println(\"Failed -> Exception\");\n");
            sb.append("            }\n");
            sb.append("            System.out.println(\"-------------------------------------------------------\");\n");
            sb.append("        }\n\n");
        }
    }

    // =========================================================================
    // Helpers
    // =========================================================================

    private void appendHelpers(StringBuilder sb) {
        sb.append("    private static boolean eq(double a, double b) {\n");
        sb.append("        return Math.abs(a - b) < 1e-9;\n");
        sb.append("    }\n\n");
        sb.append("    private static boolean eq(float a, float b) {\n");
        sb.append("        return Math.abs(a - b) < 1e-6f;\n");
        sb.append("    }\n\n");
        sb.append("    private static boolean eq(Object a, Object b) {\n");
        sb.append("        if (a == null && b == null) return true;\n");
        sb.append("        if (a == null || b == null) return false;\n");
        sb.append("        return a.equals(b);\n");
        sb.append("    }\n\n");
        sb.append("    private static boolean listToStringEq(java.util.List<?> a, java.util.List<?> b) {\n");
        sb.append("        if (a == null && b == null) return true;\n");
        sb.append("        if (a == null || b == null) return false;\n");
        sb.append("        return a.toString().equals(b.toString());\n");
        sb.append("    }\n\n");
        sb.append("    private static boolean listEq(java.util.List<?> a, java.util.List<?> b) {\n");
        sb.append("        if (a == null && b == null) return true;\n");
        sb.append("        if (a == null || b == null) return false;\n");
        sb.append("        if (a.size() != b.size()) return false;\n");
        sb.append("        for (int i = 0; i < a.size(); i++) {\n");
        sb.append("            Object ai = a.get(i), bi = b.get(i);\n");
        sb.append("            if (ai == null && bi == null) continue;\n");
        sb.append("            if (ai == null || !ai.equals(bi)) return false;\n");
        sb.append("        }\n");
        sb.append("        return true;\n");
        sb.append("    }\n\n");
        sb.append("    private static boolean setEq(java.util.Collection<?> a, java.util.Collection<?> b) {\n");
        sb.append("        if (a == null && b == null) return true;\n");
        sb.append("        if (a == null || b == null) return false;\n");
        sb.append("        return new java.util.HashSet<>(a).equals(new java.util.HashSet<>(b));\n");
        sb.append("    }\n");
    }

    // =========================================================================
    // Strategy + condition
    // =========================================================================

    private String resolveStrategy(GeneratedTestCase tc, String returnType) {
        String strategy = tc.getEqualityStrategy() != null ? tc.getEqualityStrategy() : "equals";
        if ("exception".equals(strategy)) return strategy;
        if (isListType(returnType)) {
            String elem = extractGenericType(returnType);
            return SAFE_EQUALS_TYPES.contains(elem) ? "list_equals" : "toString_equals";
        }
        return strategy;
    }

    private String buildCondition(String actual, String expected, String strategy, String javaRet) {
        return switch (strategy) {
            case "=="              -> actual + " == " + expected;
            case "eq_float"        -> "eq(" + actual + ", " + expected + ")";
            case "list_equals"     -> "listEq(" + actual + ", " + expected + ")";
            case "toString_equals" -> "listToStringEq(" + actual + ", " + expected + ")";
            case "set_equals"      -> "setEq(" + actual + ", " + expected + ")";
            default -> {
                if (isPrimitive(javaRet) && !javaRet.equals("double") && !javaRet.equals("float")) {
                    yield actual + " == " + expected;
                } else if (javaRet.equals("double") || javaRet.equals("float")) {
                    yield "eq(" + actual + ", " + expected + ")";
                } else {
                    yield "eq((Object)" + actual + ", (Object)" + expected + ")";
                }
            }
        };
    }

    // =========================================================================
    // Input description
    // =========================================================================

    private String buildInputDescription(List<String> argLiterals) {
        if (argLiterals.isEmpty()) return "\"\"";
        if (argLiterals.size() == 1) return argLiterals.get(0);
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < argLiterals.size(); i++) {
            if (i > 0) sb.append(" + \", \" + ");
            sb.append("String.valueOf(").append(argLiterals.get(i)).append(")");
        }
        return sb.toString();
    }

    // =========================================================================
    // canExtend detection
    // =========================================================================

    private boolean canExtend(QuestionSpec spec) {
        return !spec.hasParameterisedConstructor() || spec.getFields().isEmpty();
    }

    // =========================================================================
    // Arg helpers
    // =========================================================================

    private List<String> buildArgLiterals(GeneratedTestCase tc, MethodSpec method, int seed) {
        List<String> raw = (tc.getArgs() != null && !tc.getArgs().isEmpty())
                ? tc.getArgs() : buildDefaultArgs(method, seed);
        List<String> safe = new ArrayList<>();
        List<ParamSpec> params = method.getParams();
        for (int i = 0; i < params.size(); i++) {
            String arg  = i < raw.size() ? raw.get(i) : "null";
            String type = params.get(i).getType();
            if ("null".equals(arg) && isCollectionOrArray(type)) arg = safeDefault(type, seed);
            safe.add(arg);
        }
        return safe;
    }

    private List<String> buildDefaultArgs(MethodSpec method, int seed) {
        List<String> args = new ArrayList<>();
        for (ParamSpec p : method.getParams()) args.add(safeDefault(p.getType(), seed));
        return args;
    }

    private boolean isCollectionOrArray(String type) {
        if (type == null) return false;
        return type.contains("List") || type.contains("ArrayList")
            || type.contains("Map")  || type.contains("Set") || type.contains("[]");
    }

    private boolean isListType(String type) {
        if (type == null) return false;
        String t = type.trim();
        return t.startsWith("List") || t.startsWith("ArrayList")
                || t.startsWith("java.util.List") || t.startsWith("java.util.ArrayList");
    }

    private String extractGenericType(String type) {
        int lt = type.indexOf('<'), gt = type.lastIndexOf('>');
        if (lt >= 0 && gt > lt) return type.substring(lt + 1, gt).trim();
        return "Object";
    }

    private boolean isPrimitive(String type) {
        return Set.of("int","long","double","float","boolean","char","byte","short")
                  .contains(type.trim());
    }

    private String safeDefault(String type, int seed) {
        String t = type.trim();
        if (t.contains("ArrayList") || t.startsWith("List")) {
            String elem = extractGenericType(t);
            if ("String".equals(elem))
                return "new java.util.ArrayList<>(java.util.Arrays.asList(\"hello\", \"world\", \"level\"))";
            if ("Integer".equals(elem) || "int".equals(elem))
                return "new java.util.ArrayList<>(java.util.Arrays.asList(1, 2, 3))";
            return "new java.util.ArrayList<>()";
        }
        if (t.contains("Map"))    return "new java.util.HashMap<>()";
        if (t.contains("Set"))    return "new java.util.HashSet<>()";
        if (t.equals("int[]"))    return "new int[]{1, 2, 3}";
        if (t.equals("double[]")) return "new double[]{1.0, 2.0, 3.0}";
        if (t.equals("String[]")) return "new String[]{\"a\", \"b\", \"c\"}";
        return switch (t) {
            case "int", "Integer"     -> String.valueOf(seed % 10 + 1);
            case "long", "Long"       -> seed + "L";
            case "double", "Double"   -> seed + ".0";
            case "float", "Float"     -> seed + ".0f";
            case "boolean", "Boolean" -> seed % 2 == 0 ? "true" : "false";
            case "char", "Character"  -> "'a'";
            case "String"             -> "\"hello\"";
            default                   -> "null";
        };
    }

    // =========================================================================
    // Utility
    // =========================================================================

    /** Public accessor used by TestCaseReviewController. */
    public List<MethodSpec> getTestableMethods(QuestionSpec spec) {
        return pickTestableMethods(spec);
    }

    private List<MethodSpec> pickTestableMethods(QuestionSpec spec) {
        List<MethodSpec> result = new ArrayList<>();
        for (MethodSpec m : spec.getMethods()) {
            String name = m.getName();
            if (name.equals("main"))     continue;
            if (name.equals("toString")) continue;
            if (name.equals("equals"))   continue;
            if (name.equals("hashCode")) continue;
            result.add(m);
        }
        return result;
    }

    private String javaType(String raw) {
        if (raw == null) return "Object";
        return switch (raw.trim()) {
            case "Integer"   -> "int";
            case "Long"      -> "long";
            case "Double"    -> "double";
            case "Float"     -> "float";
            case "Boolean"   -> "boolean";
            case "Character" -> "char";
            default          -> raw.trim();
        };
    }
}