import java.util.*;

/**
 * AUTO-GENERATED TESTER — Q3
 * Generated by IS442 Auto-Grading System v3.5 (LLM Oracle)
 * Test cases : 4
 */
public class Q3Tester extends Q3 {

    private static double score;
    private static String qn = "Q3";

    public static void main(String[] args) {
        grade();
        System.out.println(score);
    }

    public static void grade() {
        System.out.println("-------------------------------------------------------");
        System.out.println("---------------------- " + qn + " ----------------------------");
        System.out.println("-------------------------------------------------------");

        int tcNum = 1;
        {
            try {
                ArrayList<Shape> inputs = new ArrayList<>();
                System.out.printf("Test %d: sortShapes(%s)%n", tcNum++, inputs);
                Q3.sortShapes(new java.util.ArrayList<Shape>());
                System.out.println("Expected  :|no exception|");
                System.out.println("Actual    :|no exception|");
                score += 1;
                System.out.println("Passed");
            } catch (Exception e) {
                System.out.println("Expected  :|no exception|");
                System.out.println("Actual    :|exception: " + e.getClass().getSimpleName() + "|"  );
                System.out.println("Failed");
            }
            System.out.println("-------------------------------------------------------");
        }

        {
            try {
                ArrayList<Shape> inputs = new ArrayList<>();
                System.out.printf("Test %d: sortShapes(%s)%n", tcNum++, inputs);
                Q3.sortShapes(new java.util.ArrayList<Shape>());
                System.out.println("Expected  :|no exception|");
                System.out.println("Actual    :|no exception|");
                score += 1;
                System.out.println("Passed");
            } catch (Exception e) {
                System.out.println("Expected  :|no exception|");
                System.out.println("Actual    :|exception: " + e.getClass().getSimpleName() + "|"  );
                System.out.println("Failed");
            }
            System.out.println("-------------------------------------------------------");
        }

        {
            try {
                ArrayList<Shape> inputs = new ArrayList<>();
                System.out.printf("Test %d: sortShapes(%s)%n", tcNum++, inputs);
                Q3.sortShapes(new java.util.ArrayList<Shape>());
                System.out.println("Expected  :|no exception|");
                System.out.println("Actual    :|no exception|");
                score += 1;
                System.out.println("Passed");
            } catch (Exception e) {
                System.out.println("Expected  :|no exception|");
                System.out.println("Actual    :|exception: " + e.getClass().getSimpleName() + "|"  );
                System.out.println("Failed");
            }
            System.out.println("-------------------------------------------------------");
        }

        {
            try {
                ArrayList<Shape> inputs = new ArrayList<>();
                System.out.printf("Test %d: sortShapes(%s)%n", tcNum++, inputs);
                Q3.sortShapes(new java.util.ArrayList<Shape>());
                System.out.println("Expected  :|no exception|");
                System.out.println("Actual    :|no exception|");
                score += 1;
                System.out.println("Passed");
            } catch (Exception e) {
                System.out.println("Expected  :|no exception|");
                System.out.println("Actual    :|exception: " + e.getClass().getSimpleName() + "|"  );
                System.out.println("Failed");
            }
            System.out.println("-------------------------------------------------------");
        }

    }

    private static boolean eq(double a, double b) {
        return Math.abs(a - b) < 1e-9;
    }

    private static boolean eq(float a, float b) {
        return Math.abs(a - b) < 1e-6f;
    }

    private static boolean eq(Object a, Object b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        return a.equals(b);
    }

    private static boolean listToStringEq(java.util.List<?> a, java.util.List<?> b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        return a.toString().equals(b.toString());
    }

    private static boolean listEq(java.util.List<?> a, java.util.List<?> b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        if (a.size() != b.size()) return false;
        for (int i = 0; i < a.size(); i++) {
            Object ai = a.get(i), bi = b.get(i);
            if (ai == null && bi == null) continue;
            if (ai == null || !ai.equals(bi)) return false;
        }
        return true;
    }

    private static boolean setEq(java.util.Collection<?> a, java.util.Collection<?> b) {
        if (a == null && b == null) return true;
        if (a == null || b == null) return false;
        return new java.util.HashSet<>(a).equals(new java.util.HashSet<>(b));
    }
}
